name = "kkoblas"
compatibility_date = "2024-01-01"

[env.production]
[[env.production.kv_namespaces]]
binding = "STATUS_STORE"
id = "status-store"

[env.preview]
[[env.preview.kv_namespaces]]
binding = "STATUS_STORE"
id = "status-store"
